version: '3.8'


services:
    traefik:
        image: traefik:v2.9
        container_name: traefik
        command:
            - "--log.level=DEBUG"
            - "--entrypoints.n8n.address=:${PUBLIC_PORT}"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--providers.file.directory=/configuration/"
            - "--providers.file.watch=true"
        ports:
            - "${PUBLIC_PORT}:${PUBLIC_PORT}"
        environment:
            PUBLIC_HOST: "${PUBLIC_HOST}"
            PUBLIC_PROTOCOL: "${PUBLIC_PROTOCOL}"
            PUBLIC_PORT: "${PUBLIC_PORT}"
            ADMIN_EMAIL: "${ADMIN_EMAIL}"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./traefik.yml:/configuration/dynamic.yml:ro
    
    n8n:
        container_name: n8n
        cap_drop:
            - ALL
        build:
            context: .
            args:
                DOCKER_USER: "${DOCKER_USER}"
                DOCKER_UID: "${DOCKER_UID}"
                DOCKER_GID: "${DOCKER_GID}"
        env_file:
            - .env
        volumes:
            - ./credentials/:/app/credentials:rw
            - ./workflows/:/app/workflows:rw
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.n8n.loadbalancer.server.port=80"
            - "traefik.http.routers.n8n.rule=Host(`${PUBLIC_HOST}`)"
            - "traefik.http.routers.n8n.tls=${USE_TLS}"
            - "traefik.http.routers.n8n.tls.certresolver=letsencrypt"
