version: '3.8'


services:
    # /n8n
    n8n:
        container_name: n8n
        ports:
            - 80:80
        build:
            context: .
            args:
                DOCKER_USER: "${DOCKER_USER}"
                DOCKER_UID: "${DOCKER_UID}"
                DOCKER_GID: "${DOCKER_GID}"
        labels:
            - "traefik.enable=true"
        volumes:
            - ./credentials/:/app/credentials:rw
            - ./workflows/:/app/workflows:rw
    