version: '3.8'


services:
    traefik:
        image: traefik:v2.9
        container_name: traefik
        command:
            - "--log.level=DEBUG"
            - "--entrypoints.n8n.address=:${PUBLIC_PORT}"
            - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
            - "--certificatesresolvers.letsencrypt.acme.email=${ADMIN_EMAIL}"
            - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
            - "--providers.file.directory=/configuration/"
            - "--providers.file.watch=true"
        ports:
            - "${PUBLIC_PORT}:${PUBLIC_PORT}"
        read_only: true
        user: "${DOCKER_UID}:${DOCKER_GID}"
        cap_drop:
            - ALL
        cap_add:
            - NET_BIND_SERVICE
        security_opt:
            - "no-new-privileges:true"
        env_file:
            - .env
        volumes:
            - "./letsencrypt:/letsencrypt"
            - ./dynamic.yml:/configuration/dynamic.yml:ro
        networks:
            - foo
    
    n8n:
        container_name: n8n
        cap_drop:
            - ALL
        build:
            context: .
            args:
                DOCKER_USER: "${DOCKER_USER}"
                DOCKER_UID: "${DOCKER_UID}"
                DOCKER_GID: "${DOCKER_GID}"
        env_file:
            - .env
        expose:
            - 80
        volumes:
            - ./credentials/:/app/credentials:rw
            - ./workflows/:/app/workflows:rw
        networks:
            - foo

networks:
    foo:
