version: '3.8'


services:
    n8n:
        container_name: n8n
        cap_drop:
            - ALL
        ports:
            - 80:80
        build:
            context: .
            args:
                DOCKER_USER: "${DOCKER_USER}"
                DOCKER_UID: "${DOCKER_UID}"
                DOCKER_GID: "${DOCKER_GID}"
        env_file:
            - .env
        volumes:
            - ./credentials/:/app/credentials:rw
            - ./workflows/:/app/workflows:rw
    