version: '3.8'


services:
    traefik:
        image: traefik:v2.9
        container_name: traefik
        command:
            - "--entrypoints.n8n.address=:${PUBLIC_PORT}"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
            - "--certificatesresolvers.letsencrypt.acme.email=${ADMIN_EMAIL}"
            - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
        ports:
            - "${PUBLIC_PORT}:${PUBLIC_PORT}"
        volumes:
            - "./letsencrypt:/letsencrypt"
            - /var/run/docker.sock:/var/run/docker.sock:ro
    
    n8n:
        container_name: n8n
        cap_drop:
            - ALL
        build:
            context: .
            args:
                DOCKER_USER: "${DOCKER_USER}"
                DOCKER_UID: "${DOCKER_UID}"
                DOCKER_GID: "${DOCKER_GID}"
        env_file:
            - .env
        volumes:
            - ./credentials/:/app/credentials:rw
            - ./workflows/:/app/workflows:rw
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.n8n.rule=Host(`${PUBLIC_HOST}`)"
            - "traefik.http.routers.n8n.entrypoints=n8n"
            - "traefik.http.routers.n8n.tls=${USE_TLS}"
            - "traefik.http.routers.n8n.tls.certresolver=letsencrypt"
            - "traefik.http.middlewares.n8n.basicauth.users=${BASIC_AUTH}"
            - "traefik.http.routers.n8n.middlewares=n8n@docker"
